const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const qs=new URLSearchParams(location.search),groupId=qs.get('group'),groupName=qs.get('name')||'الغرفة الصوتية';
let user,profile,channel,stream,muted=false,hand=false,startedAt=Date.now(),peers=new Map(),unread=0;
const topics=['What made you smile today?','What is your dream travel destination?','Describe your perfect weekend.','What new English word did you learn?','Would you rather live by the sea or in the mountains?','Tell us about your favorite food.'];let topicIndex=0;
function toast(t){$('roomToast').textContent=t;$('roomToast').classList.add('show');setTimeout(()=>$('roomToast').classList.remove('show'),2200)}
async function init(){if(!groupId){location.href='groups.html';return}const{data:{user:u}}=await supabaseClient.auth.getUser();if(!u){location.href='login.html';return}user=u;const{data:membership}=await supabaseClient.from('group_members').select('id').eq('group_id',groupId).eq('user_id',u.id).maybeSingle();if(!membership){alert('هذه الغرفة متاحة لأعضاء المجموعة فقط.');location.href='groups.html';return}const{data:p}=await supabaseClient.from('profiles').select('id,display_name').eq('id',u.id).maybeSingle();profile=p||{id:u.id,display_name:u.user_metadata?.name||'مستخدم'};$('roomName').textContent=groupName;try{stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false})}catch(e){alert('اسمح للموقع باستخدام الميكروفون ثم حاول مرة أخرى.');location.href='groups.html';return}connect();setInterval(updateTimer,1000)}
function connect(){channel=supabaseClient.channel(`voice-group-${groupId}`,{config:{presence:{key:user.id},broadcast:{self:false}}});channel.on('presence',{event:'sync'},renderPeople).on('presence',{event:'leave'},({key})=>removePeer(key)).on('broadcast',{event:'voice-signal'},({payload})=>signal(payload)).on('broadcast',{event:'room-chat'},({payload})=>addMessage(payload)).subscribe(async s=>{if(s==='SUBSCRIBED'){await channel.track({user_id:user.id,name:profile.display_name,role:'speaker',muted,hand});send({kind:'join'})}})}
const send=m=>channel?.send({type:'broadcast',event:'voice-signal',payload:{...m,sender_id:user.id}});
function peer(id){if(peers.has(id))return peers.get(id);const pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun1.l.google.com:19302'}]}),x={pc,q:[]};peers.set(id,x);stream.getTracks().forEach(t=>pc.addTrack(t,stream));pc.onicecandidate=e=>e.candidate&&send({kind:'candidate',target_id:id,candidate:e.candidate});pc.ontrack=e=>{let a=document.querySelector(`audio[data-u="${id}"]`);if(!a){a=document.createElement('audio');a.autoplay=true;a.dataset.u=id;$('remoteAudioContainer').appendChild(a)}a.srcObject=e.streams[0]};pc.onconnectionstatechange=()=>['failed','closed'].includes(pc.connectionState)&&removePeer(id);return x}
async function signal(s){if(s.sender_id===user.id||(s.target_id&&s.target_id!==user.id))return;try{if(s.kind==='join'){const p=peer(s.sender_id),o=await p.pc.createOffer();await p.pc.setLocalDescription(o);send({kind:'offer',target_id:s.sender_id,description:p.pc.localDescription})}else if(s.kind==='offer'){const p=peer(s.sender_id);await p.pc.setRemoteDescription(s.description);await flush(p);const a=await p.pc.createAnswer();await p.pc.setLocalDescription(a);send({kind:'answer',target_id:s.sender_id,description:p.pc.localDescription})}else{const p=peer(s.sender_id);if(s.kind==='answer'){await p.pc.setRemoteDescription(s.description);await flush(p)}else if(s.kind==='candidate'){p.pc.remoteDescription?await p.pc.addIceCandidate(s.candidate):p.q.push(s.candidate)}}}catch(e){console.error(e)}}
async function flush(p){while(p.q.length)await p.pc.addIceCandidate(p.q.shift())}function removePeer(id){peers.get(id)?.pc.close();peers.delete(id);document.querySelector(`audio[data-u="${id}"]`)?.remove()}
function renderPeople(){const people=Object.values(channel.presenceState()).flat(),speakers=people.filter(x=>x.role!=='listener'),listeners=people.filter(x=>x.role==='listener');$('speakerCount').textContent=`${speakers.length}/6`;$('audienceCount').textContent=listeners.length;$('speakerGrid').innerHTML=speakers.map(x=>`<article class="speaker"><div class="avatar-wrap"><div class="avatar">${esc((x.name||'م')[0])}</div><span class="mic-state">${x.muted?'🔇':'🎙️'}</span></div><h3>${esc(x.user_id===user.id?'أنت':x.name)}</h3><p>${x.hand?'✋ يطلب التحدث':'متحدث'}</p></article>`).join('')||'<p class="empty-note">لا يوجد متحدثون</p>';$('audienceList').innerHTML=listeners.map(x=>`<span class="audience-person"><i>${esc((x.name||'م')[0])}</i>${esc(x.name)}</span>`).join('')||'<p class="empty-note">لا يوجد مستمعون حاليًا</p>'}
async function updatePresence(){await channel.track({user_id:user.id,name:profile.display_name,role:'speaker',muted,hand})}
function toggleMute(){muted=!muted;stream.getAudioTracks().forEach(t=>t.enabled=!muted);$('muteBtn').classList.toggle('active',muted);$('muteBtn').innerHTML=muted?'<span>🔇</span><small>تشغيل</small>':'<span>🎙️</span><small>كتم</small>';updatePresence()}
function toggleHand(){hand=!hand;$('handBtn').classList.toggle('active',hand);$('handBtn').innerHTML=hand?'<span>✋</span><small>أنزل يدك</small>':'<span>✋</span><small>ارفع يدك</small>';updatePresence();toast(hand?'تم رفع يدك':'تم إنزال يدك')}
function addMessage(m){const d=document.createElement('div');d.className='room-msg';d.innerHTML=`<strong>${esc(m.name)}</strong><p>${esc(m.text)}</p>`;$('roomMessages').appendChild(d);$('roomMessages').scrollTop=$('roomMessages').scrollHeight;if(!$('sidePanel').classList.contains('show')){$('chatBadge').hidden=false;$('chatBadge').textContent=++unread}}
async function leave(){stream?.getTracks().forEach(t=>t.stop());for(const id of peers.keys())removePeer(id);if(channel){await channel.untrack();await supabaseClient.removeChannel(channel)}location.href='groups.html'}
function updateTimer(){const s=Math.floor((Date.now()-startedAt)/1000);$('roomTimer').textContent=`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
$('backBtn').onclick=leave;$('leaveBtn').onclick=leave;$('muteBtn').onclick=toggleMute;$('handBtn').onclick=toggleHand;$('nextTopicBtn').onclick=()=>{$('topicText').textContent=topics[++topicIndex%topics.length]};$('chatBtn').onclick=()=>{$('sidePanel').classList.add('show');unread=0;$('chatBadge').hidden=true};$('closeChatBtn').onclick=()=>$('sidePanel').classList.remove('show');$('shareBtn').onclick=async()=>{try{await navigator.clipboard.writeText(location.href);toast('تم نسخ رابط الغرفة')}catch{toast('تعذر نسخ الرابط')}};$('roomMessageForm').onsubmit=e=>{e.preventDefault();const i=$('roomMessageInput'),text=i.value.trim();if(!text)return;const m={name:profile.display_name,text,sender_id:user.id};channel.send({type:'broadcast',event:'room-chat',payload:m});addMessage(m);i.value=''};window.addEventListener('beforeunload',()=>{stream?.getTracks().forEach(t=>t.stop())});init();
